[package]
name = "biomemap-tileserver"
version = "0.1.0"
edition = "2024"

[dependencies]
cubiomes = { version = "0.3.3" }
image = "0.25"
actix-web = "4.0"
actix-files = "0.6"
tokio = "1.0"
tokio-stream = "0.1"
